### ISSUE TITLE
TypeError：sub() function can not be execute. How can you fix it? 

### ISSUE THREAD

**Issue by ChacesXia** [KaleidoZhouYN/e2e-joint-face-detection-and-alignment#2]
https://github.com/KaleidoZhouYN/e2e-joint-face-detection-and-alignment/blob/f2c29b2e2429ae58d212e9fff38440fa1da5e44e/predict_m.py#L196

In here, `ldmks[:,index_y] = ldmks[:,index_y] * w - pad1`;  `lamks[:,index_y]*w` is a tensor, but `pad1` is a number. So the sub() function can not be execute. How to fix it??

**Comment by KaleidoZhouYN** [comment]
you need to upgrade your pytorch version

**Comment by ChacesXia** [comment]
Which version should I upgrade to at least??
My current version :
pytorch                   0.4.1           py36_cuda90_cudnn7he774522_1    pytorch

**Comment by SyGoing** [comment]
> Which version should I upgrade to at least??
> My current version :
> pytorch 0.4.1 py36_cuda90_cudnn7he774522_1 pytorch

hello you can fix it by change the code like this:
          # ldmks[:,index_y] = ldmks[:,index_y] * w - pad1
            tmp=(ldmks[:,index_y]).numpy()
            tensor=np.ones(tmp.shape,np.float32)*pad1
            tensor_pad1=torch.from_numpy(tensor)
            ldmks[:,index_y] = ldmks[:,index_y] * w - tensor_pad1

**Comment by KaleidoZhouYN** [comment]
not sure what your problem is,but the pytorch doc say that there won't be problem for substraction of a tensor and a number. See torch.add()

**Comment by ChacesXia** [comment]
Thanks for you, I have fixed it based on @SyGoing 's method. 
We can wrap pad1 to tensor form.
